version: '3.5'

services:
    
    nginx:
        image: nginx:stable
        container_name: nginx
        volumes:
            - ./application:/var/www
            - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - web-network
        restart: unless-stopped

    php-fpm:
        image: php:fpm
        container_name: php-fpm
        volumes:
            - ./application:/var/www
        working_dir: /var/www
        networks:
            - web-network
        restart: unless-stopped

    composer:
        image: composer
        container_name: composer
        volumes:
            - ./application:/app
        command: "install"
        entrypoint: /docker-entrypoint.sh

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        ports:
            - "3306:3306"
        volumes:
            - ./storage/db:/var/lib/mysql
        command: "--innodb_use_native_aio=0"
        restart: unless-stopped

networks:
    web-network:
        driver: bridge
