version: '3.5'

services:
    
    nginx:
        image: nginx:stable
        container_name: nginx
        volumes:
            - ./application/public/:/var/www/public/
            - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - web-network
        restart: unless-stopped

    php-fpm:
        image: php:fpm
        container_name: php-fpm
        volumes:
            - ./application/public/:/var/www/public/
        networks:
            - web-network
        restart: unless-stopped

networks:
    web-network:
        driver: bridge