version: '3.5'

services:
    
    nginx:
        image: nginx:stable
        depends_on:
            - php-fpm
        volumes:
            - ./application:/var/www
            - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www
        ports:
            - "80:80"
            - "443:443"
        networks:
            - web-network
        restart: unless-stopped

    php-fpm:
        build: ./environment/php-fpm
        depends_on:
            - mysql
        volumes:
            - ./application:/var/www
        working_dir: /var/www
        networks:
            - web-network
        restart: unless-stopped

    mysql:
        build: ./environment/mysql
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - ./storage/db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - web-network
        restart: unless-stopped

networks:
    web-network:
        driver: bridge
