version: '3.5'

services:
    
    nginx:
        image: nginx:stable
        container_name: nginx
        volumes:
            - ./application/:/var/www/
            - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - web-network
        restart: unless-stopped

    php-fpm:
        image: php:fpm
        container_name: php-fpm
        volumes:
            - ./application/:/var/www/
        working_dir: /var/www
        networks:
            - web-network
        restart: unless-stopped

    composer:
        image: composer
        container_name: composer
        build: ./application/
        volumes:
            - ./application/:/app/
        command: install
        entrypoint: /docker-entrypoint.sh

networks:
    web-network:
        driver: bridge
