FROM php:5.6.40-fpm
RUN apt-get update && apt-get install -y \
	libzip-dev \
	libfreetype6-dev \
	libjpeg62-turbo-dev \
	libpng-dev \
	libmcrypt-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j$(nproc) bcmath mysqli pdo pdo_mysql zip gd mcrypt